x-app: &default-app
  build:
    target: debug
  image: codepraise-clone-notifier-python:debug
  volumes:
    - .:/worker
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_REGION
    - REPORT_QUEUE
    - SLACK_WEBHOOK_URL

services:
  # `$ docker compose run --rm worker`
  worker:
    <<: *default-app
    command: inv worker -e ${ENV:-development}

  # `$ docker compose run --rm console`
  console:
    <<: *default-app
    profiles:
      - debug
    command: inv console -e ${ENV:-development}

  # `$ docker compose run --rm bash`
  bash:
    <<: *default-app
    tty: true
    profiles:
      - debug
    command: bash
