services:
  worker:
    build: .
    image: codepraise-clone-notifier-python
    volumes:
      - ./config:/worker/config
    environment:
      - ENV=production
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - REPORT_QUEUE
