name: Build Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/cache@v2
      id: cache
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('**/Pipfile.lock') }}-docs
    - name: Install Material for MkDocs
      if: steps.cache.outputs.cache-hit != 'true'
      run: pip install mkdocs-material 
    - name: Build Docs
      run: mkdocs gh-deploy --force
